METHODS	:=							\
	create_null						\
	config_screen_size				\
	config_camera_size				\
	config_camera_center			\
	config_fractal_fn				\
	configure						\
	configure_default				\
	start							\
	init_mlx							\
	destroy							\
	evaluate						\
	draw							\
	onzoom							\
	onloop							\
	move_camera						\
	move_iterator_constant			\
	toggle_antialias				\
	change_max_iteration			\
	onkeypress						\
	set_hooks						\
	show_console					\
	print_camera_data_on_screen		\
	print_iterator_data_on_screen	\
	exit

include ../Makefile
