METHODS	:=					\
	create_null				\
	config_screen_size		\
	config_fractal_fn		\
	configure				\
	configure_default		\
	start					\
	init					\
	destroy					\
	evaluate				\
	draw					\
	onzoom					\
	onloop					\
	move_camera				\
	move_iterator_constant	\
	onkeypress				\
	set_hooks				\
	exit

include ../Makefile
